### ISSUE TITLE
Can not install the addon with blender 2.83.4

### ISSUE THREAD

**Issue by BennyGovaerts** [Jack-Cooke/blign#5]
Can not install the addon with blender 2.83.4

**Comment by BennyGovaerts** [comment]
Only if you manual copy the content to the addon directory , but not if you install from .zip

**Comment by Jack-Cooke** [comment]
Yes sorry I'm not sure how to make the addon installable from a .zip file. It only works when the .py file is installed. I'll do some research and try to fix this soon!

**Comment by BennyGovaerts** [comment]
Works fine if you install it manual ( no big deal for me )
